DATABASE_URL: "postgresql://postgres:supabase-wekruit@db.lwpywijwzqsuhswybcbm.supabase.co:5432/postgres"
REDIS_URL: "rediss://default:Ab8qAAIncDEwODYxYzFkYjU0Y2Q0MjlhYmUyNGI3N2M4NzIwM2RiNnAxNDg5Mzg@unbiased-seasnail-48938.upstash.io:6379"
JWT_SECRET: "random string for your JWT secret, make it long"
TEMPORAL_ADDRESS: "wecrew-temporal.fly.dev:7233"
FIREBASE_PROJECT_ID: "wecrew-axon"
FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@wecrew-axon.iam.gserviceaccount.com"
FRONTEND_URL: "https://axon-wecrew.vercel.app"
NEXT_PUBLIC_BACKEND_URL: "https://axon-backend-wecrew-axon.us-west1.run.app"
BACKEND_INTERNAL_URL: "https://axon-backend-wecrew-axon.us-west1.run.app"
NODE_ENV: "production"
